name: Render video
on:
  workflow_dispatch:
    inputs:
      sketches:
        required: true
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "alexanderl19/alexanderliu"
          token: ${{ secrets.GH_PAT }}
          path: "alexanderliu"
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - uses: pnpm/action-setup@v2
      - run: |
          cd ./alexanderliu/apps/video-github-profile
          pnpm install --frozen-lockfile --filter apps/video-github-profile
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: |
          cd ./alexanderliu/apps/video-github-profile
          pnpm run build --props="./input-props.json"
      - uses: actions/upload-artifact@v2
        with:
          name: out.gif
          path: out/video.gif
