name: Render video
on:
  workflow_dispatch:
    inputs:
      sketches:
        required: true
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "alexanderl19/alexanderliu"
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-node@v4
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
            - args: [--frozen-lockfile, --filter, apps/video-github-profile]
      - run: |
          cd ./apps/video-github-profile
          echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: |
          cd ./apps/video-github-profile
          pnpm run build --props="./input-props.json"
      - uses: actions/upload-artifact@v4
        with:
          name: out.gif
          path: apps/video-github-profile/out/video.gif
          compression-level: 0
